# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand(7,7)
tensor

tensor([[0.9293, 0.4623, 0.1808, 0.9476, 0.9078, 0.6547, 0.0579],
        [0.5673, 0.7505, 0.0863, 0.0526, 0.8926, 0.3115, 0.8961],
        [0.8194, 0.0179, 0.3016, 0.5321, 0.0166, 0.7332, 0.5285],
        [0.0027, 0.2270, 0.7462, 0.6672, 0.0608, 0.1727, 0.4371],
        [0.3780, 0.6767, 0.9505, 0.1742, 0.7744, 0.1829, 0.8872],
        [0.6584, 0.7910, 0.0237, 0.9977, 0.5694, 0.1277, 0.4683],
        [0.3908, 0.0599, 0.6912, 0.4228, 0.8382, 0.3217, 0.3702]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor

tensor_b = torch.rand(1,7)
# Perform matrix multiplication 
torch.mm(tensor, tensor_b.T)

tensor([[3.0377],
        [2.3272],
        [2.2537],
        [1.8008],
        [2.8193],
        [2.6806],
        [2.3549]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [6]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor1 = torch.rand(7,7)
tensor2 = torch.rand(1,7)

# Matrix multiply tensors
torch.mm(tensor1, tensor2.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [10]:
# Set random seed on the GPU
#torch.cuda.manual_seed(1234) # For Cuda
torch.mps.manual_seed(1234) # For Apple silicon


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [11]:
# Set random seed
torch.manual_seed(1234)
tensor1 = torch.rand(2,3)
tensor2 = torch.rand(2,3)

# Check for access to GPU
device = 'mps' if torch.backends.mps.is_available() else 'cpu'

# Create two random tensors on GPU
tensor1_gpu = tensor1.to(device)
tensor2_gpu = tensor2.to(device)

tensor1_gpu, tensor2_gpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='mps:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='mps:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [18]:
# Perform matmul on tensor_A and tensor_B
result = torch.mm(tensor1_gpu, tensor2_gpu.T)
result

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='mps:0')

### 8. Find the maximum and minimum values of the output of 7.

In [21]:
# Find max
# Find min
result.max(), result.min()


(tensor(0.5617, device='mps:0'), tensor(0.3647, device='mps:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [20]:
# Find arg max
# Find arg min
result.argmax(), result.argmin()

(tensor(3, device='mps:0'), tensor(0, device='mps:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [22]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random = torch.rand(1,1,1,10)

# Remove single dimensions
random_removed = random.squeeze()

# Print out tensors and their shapes
print(random, random.shape)
print(random_removed, random_removed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
